[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
evm_version = "paris"
runs = 100_000
viaIr = true

remappings = [
    "@openzeppelin=lib/openzeppelin-contracts/contracts",
    "@solmate=lib/solmate/src",
]

[rpc_endpoints]
optimism = "${OP_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
